#!/usr/bin/env bash
# Installs nginx and configures it on a remote server
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!
## As an answer file, write a Bash script that configures a new Ubuntu machine\
## Don't use systemctl for restarting nginx

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
