#!/usr/bin/env bash
# Configures Nginx
# Script configures a new machine
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install nginx

# replace the index.html file content 
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# handle redirection
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# handle error 404
sudo sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# shellcheck disable=SC2154
# add custom header
sudo sed -i "/server_name _;/a \        add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

# start nginx
sudo service nginx restart

~                            
