#!/usr/bin/env bash
# Configures Nginx
# Script configures a new machine
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

#  create the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# create a webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
# handle redirection
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.medium.com/@nma-nwadinobi permanent;' /etc/nginx/sites-available/default

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
