#!/usr/bin/env bash
# Install and configure HAProxy on individual server
sudo apt-get update
sudo apt-get install -y haproxy

echo "
frontend safeville.tech
  bind *:80
  default_backend webservers

backend webservers
  balance roundrobin
  server web-01 54.83.164.94-web-01:80 check
  server web-02 54.165.18.70-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
