#!/usr/bin/env bash
# Install and configure HAProxy on individual server
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  safeville-frontend
        bind *:80
        mode http
        default_backend safeville-backend
backend safeville-backend
        balance roundrobin
        server 184030-web-01 100.25.19.204:80 check
        server 184030-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
