#!/usr/bin/env bash
# Install and configure HAProxy on individual server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Enable load balancer
sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy

# Config load balancer with web servers
sudo sed -i "$ a\ \nfrontend load_balancer\n\tbind\t0.0.0.0:80\n\tmode\thttp\n\tdefault_backend\tweb_servers\n\nbackend web_servers\n\tbalance\troundrobin\n\tserver\t18403-web-01\t100.26.241.132:80\n\tserver\t18403-web-02\t35.153.93.93" /etc/haproxy/haproxy.cfg

sudo service haproxy start
