#!/usr/bin/env bash
# Script that configures the container to run Nginx as Nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo pkill -f apache2
sudo -u nginx nginx
